pipeline:
  backendBuild:
    image: "java:openjdk-8-jdk-alpine"
    commands:
      - ./gradlew clean assemble
    volumes:
      - /home/qnoa-build/drone-data:/var/lib/drone
    environment:
      - GRADLE_USER_HOME=/var/lib/drone/cache
  deploy:
    image: "java:openjdk-8-jdk-alpine"
    commands:
      - ./gradlew clean mk-schema:bintrayUpload
      - ./gradlew clean mk-core:bintrayUpload
    volumes:
      - /home/qnoa-build/drone-data:/var/lib/drone
    secrets: [bintray_user, bintray_key]
    environment:
      - GRADLE_USER_HOME=/var/lib/drone/cache
    when:
      event: tag
  telegram:
    image: appleboy/drone-telegram
    secrets: [telegram_token, telegram_to]
    when:
      status: [success, failure]
